# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Publish GH pages
run-name: Publish GH pages by ${{ github.actor }}

on:
  push:
    branches:
      - main

concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
    deploy:
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      steps:
        - name: Repo checkout
          uses: actions/checkout@v4

        - name: Install node clean install
          run: npm ci

        - name: run build
          run: npm run build
          env:
            NODE_ENV: production

        - name: Upload artifact
          uses: actions/upload-pages-artifact@v2
          with:
            path: '.'
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v3